import type { CSSProperties } from "react";

export const s = {
  drop: (over: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "38px 20px",
    borderRadius: 10,
    border: "1.5px dashed " + (over ? "var(--accent)" : "var(--border-strong)"),
    background: over ? "var(--accent-bg)" : "var(--bg-elevated)",
    textAlign: "center",
  }),
  dropTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  dropBody: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  hiddenInput: { display: "none" } satisfies CSSProperties,
  error: {
    marginTop: 12,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  fields: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "18px 0 8px",
  } satisfies CSSProperties,
  preview: {
    maxHeight: 280,
    overflow: "auto",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  ignoredList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  ignoredItem: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    textDecorationLine: "line-through",
  } satisfies CSSProperties,
  ignoredBody: { fontSize: 11.5, color: "var(--text-muted)", marginTop: 6, lineHeight: 1.5 } satisfies CSSProperties,
  footer: { display: "flex", gap: 8, width: "100%", alignItems: "center" } satisfies CSSProperties,
  footerSpacer: { marginLeft: "auto" } satisfies CSSProperties,
} as const;
