import type { CSSProperties } from "react";

export const s = {
  page: { padding: "20px 28px 40px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 16,
  } satisfies CSSProperties,
  title: { margin: 0, fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  body: { display: "grid", gridTemplateColumns: "minmax(260px, 340px) minmax(0, 1fr)", gap: 20 } satisfies CSSProperties,
  filter: {
    width: "100%",
    padding: "6px 10px",
    marginBottom: 12,
    fontSize: 13,
    color: "var(--text-primary)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  groupLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "var(--text-muted)",
    margin: "10px 0 6px",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  row: (active: boolean): CSSProperties => ({
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "6px 10px",
    fontSize: 13,
    borderRadius: 6,
    color: "var(--text-primary)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  path: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  tokens: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  preview: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "14px 18px",
    minHeight: 200,
    minWidth: 0,
    overflowX: "auto",
    fontSize: 14,
  } satisfies CSSProperties,
  previewMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  message: { fontSize: 13, color: "var(--text-secondary)", margin: "8px 0" } satisfies CSSProperties,
  footer: { marginTop: 16, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
