import type { CSSProperties } from "react";

export const s = {
  card: (accepted: boolean) =>
    ({
      display: "flex",
      gap: 16,
      padding: 16,
      marginBottom: 12,
      borderRadius: 9,
      background: "var(--bg-elevated)",
      borderTop: "1px solid var(--border)",
      borderRight: "1px solid var(--border)",
      borderBottom: "1px solid var(--border)",
      borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border)"}`,
    }) satisfies CSSProperties,
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  category: {
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  rule: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    letterSpacing: "-0.01em",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  editRow: { display: "flex", gap: 8, marginTop: 8 } satisfies CSSProperties,
  evidence: {
    marginTop: 10,
    borderRadius: 7,
    border: "1px solid var(--border)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "5px 10px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  copy: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
  } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 11.5,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    overflow: "auto",
  } satisfies CSSProperties,
  confidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  } satisfies CSSProperties,
  confidenceLabel: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  confidenceBar: { width: 90 } satisfies CSSProperties,
  confidenceValue: { fontSize: 11, color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: {
    width: 150,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 7,
  } satisfies CSSProperties,
} as const;
