import type { CSSProperties } from "react";

export const b = {
  layout: { display: "flex", gap: 28, alignItems: "flex-start", flexWrap: "wrap" } satisfies CSSProperties,
  tocWrap: { width: 180, flexShrink: 0, alignSelf: "stretch" } satisfies CSSProperties,
  toc: { position: "sticky", top: 16 } satisfies CSSProperties,
  tocLabel: { fontSize: 10.5, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  tocItem: (active: boolean): CSSProperties => ({
    display: "block",
    width: "100%",
    background: "none",
    border: 0,
    borderLeft: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    padding: "5px 0 5px 11px",
    textAlign: "left",
    font: "inherit",
    fontSize: 12.5,
    fontWeight: active ? 600 : 500,
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    cursor: "pointer",
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  stack: { display: "flex", flexDirection: "column", gap: 7, marginTop: 4 } satisfies CSSProperties,
  pathRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 11px", borderRadius: 7, background: "var(--bg-surface)" } satisfies CSSProperties,
  icon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  pathReason: { fontSize: 12, color: "var(--text-secondary)", flex: 1, minWidth: 0 } satisfies CSSProperties,
  cmdList: { listStyle: "none", margin: "4px 0 0", padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  cmdRow: { display: "flex", alignItems: "center", gap: 10, padding: "9px 12px", borderRadius: 7, background: "var(--code-bg)", border: "1px solid var(--border)" } satisfies CSSProperties,
  cmdNum: { fontSize: 11, color: "var(--text-muted)", width: 14 } satisfies CSSProperties,
  cmdText: { flex: 1, minWidth: 0, display: "flex", alignItems: "baseline", flexWrap: "wrap", gap: "2px 10px" } satisfies CSSProperties,
  cmd: { fontSize: 12, color: "var(--text-primary)" } satisfies CSSProperties,
  cmdMuted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  cwd: { fontSize: 11, color: "var(--text-muted)", border: "1px solid var(--border)", borderRadius: 4, padding: "0 6px" } satisfies CSSProperties,
  readList: { listStyle: "none", margin: "4px 0 0", padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  readItem: { display: "flex", gap: 11, alignItems: "flex-start" } satisfies CSSProperties,
  readNum: { width: 20, height: 20, borderRadius: 99, background: "var(--accent-bg)", color: "var(--accent)", fontSize: 11, fontWeight: 700, display: "grid", placeItems: "center", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  readReason: { fontSize: 12.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  empty: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  cards: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 10, marginTop: 4 } satisfies CSSProperties,
  card: { padding: 12, borderRadius: 8, border: "1px solid var(--border)", background: "var(--bg-surface)" } satisfies CSSProperties,
  cardTitle: { fontSize: 13, fontWeight: 600, lineHeight: 1.35 } satisfies CSSProperties,
  cardScope: { display: "block", fontSize: 11, color: "var(--text-muted)", margin: "7px 0" } satisfies CSSProperties,
  badge: { border: "1px solid var(--border-strong)" } satisfies CSSProperties,
};
